name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/geopjr/crystal-gtk:latest
    steps:
      - uses: actions/checkout@v2
      - name: Shards install
        run: shards install
      - name: Generate gresource
        run: make gresource
      - name: Spec
        run: crystal spec || exit 1
      - name: Check formatting
        run: crystal tool format --check
