name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/geopjr/crystal-gtk:latest
    steps:
      - uses: actions/checkout@v2
      - name: Shards install
        run: shards install
      - name: Generate gresource
        run: make gresource || wget "https://raw.githubusercontent.com/GeopJr/GeopJr/main/collision.gresource" -O data/dev.geopjr.Collision.gresource
      - name: Spec
        run: crystal spec -Dpreview_mt --order random || exit 1
      - name: Check formatting
        run: crystal tool format --check
